name: Deploy All Branches
on:
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: pages-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Prepare folder
        run: |
          mkdir out
          rsync -av --exclude='.git' --exclude='.github' ./ out/

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_dir: ${{ github.ref_name }}
          keep_files: true
