name: Deploy All Branches
on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          mkdir -p public

          target="public/${{ github.ref_name }}"
          mkdir -p "$target"
          

          rsync -av --exclude='.git' --exclude='.github' --exclude='public' . "$target/"
          

          if [ "${{ github.ref_name }}" == "main" ]; then
             cp "$target/main.html" public/index.html
          fi
          


          find "$target" -type f -name "*.html" -exec sed -i 's|href="/|href="|g' {} +
          find "$target" -type f -name "*.html" -exec sed -i 's|src="/|src="|g' {} +
          
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - uses: actions/deploy-pages@v4
