name: Deploy All Branches
on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          mkdir -p public

          target="public/${{ github.ref_name }}"
          mkdir -p "$target"
          find . -maxdepth 1 -not -name 'public' -not -name '.git' -not -name '.github' -exec cp -r {} "$target/" \;

          find "$target" -name "*.html" -exec sed -i 's|href="/|href="|g' {} +
          find "$target" -name "*.html" -exec sed -i 's|src="/|src="|g' {} +

          if [ "${{ github.ref_name }}" == "main" ]; then
             cp "$target/main.html" public/index.html
          fi
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - uses: actions/deploy-pages@v4
